const wordList = [
  { hint: "Its used in AI mostly", word: "python" },
  { hint: "Its a markup language", word: "html" },
  { hint: "Styling language for web pages", word: "css" },
  { hint: "Programming language for web interactivity", word: "javascript" },
  { hint: "Backend runtime for JavaScript", word: "nodejs" },
  { hint: "Used for database queries", word: "sql" },
  { hint: "Version control system", word: "git" },
  { hint: "Platform to host repositories", word: "github" },
  { hint: "JavaScript framework by Meta", word: "react" },
  { hint: "Frontend framework by Google", word: "angular" },

  { hint: "Server-side language by Microsoft", word: "csharp" },
  { hint: "Object-oriented language used in enterprise apps", word: "java" },
  { hint: "Low-level programming language", word: "c" },
  { hint: "Extension of C with OOP features", word: "cpp" },
  { hint: "Used for iOS development", word: "swift" },
  { hint: "Used for Android development", word: "kotlin" },
  { hint: "Scripting language for automation", word: "bash" },
  { hint: "Used for statistical computing", word: "r" },
  { hint: "Language for blockchain smart contracts", word: "solidity" },
  { hint: "Query language for APIs", word: "graphql" },

  { hint: "NoSQL database by MongoDB Inc.", word: "mongodb" },
  { hint: "Popular relational database", word: "mysql" },
  { hint: "Open-source relational database", word: "postgresql" },
  { hint: "In-memory data store", word: "redis" },
  { hint: "Search engine database", word: "elasticsearch" },

  { hint: "Tool for containerization", word: "docker" },
  { hint: "Container orchestration platform", word: "kubernetes" },
  { hint: "Cloud computing platform by Amazon", word: "aws" },
  { hint: "Cloud platform by Google", word: "gcp" },
  { hint: "Cloud platform by Microsoft", word: "azure" },

  { hint: "CI/CD automation tool", word: "jenkins" },
  { hint: "Popular code editor by Microsoft", word: "vscode" },
  { hint: "Lightweight code editor", word: "sublime" },
  { hint: "Terminal-based text editor", word: "vim" },
  { hint: "Another terminal editor", word: "nano" },

  { hint: "Package manager for JavaScript", word: "npm" },
  { hint: "Alternative JS package manager", word: "yarn" },
  { hint: "Build tool for modern web apps", word: "vite" },
  { hint: "Module bundler", word: "webpack" },
  { hint: "Transpiler for JavaScript", word: "babel" },

  { hint: "Testing framework for JavaScript", word: "jest" },
  { hint: "End-to-end testing tool", word: "cypress" },
  { hint: "API testing tool", word: "postman" },
  { hint: "Design tool for UI/UX", word: "figma" },
  { hint: "Graphic design software", word: "photoshop" },

  { hint: "Operating system kernel", word: "linux" },
  { hint: "Popular OS by Apple", word: "macos" },
  { hint: "Popular OS by Microsoft", word: "windows" },
  { hint: "Mobile OS by Google", word: "android" },
  { hint: "Mobile OS by Apple", word: "ios" },
];
